heading levels updated
mlibrary/lib.umich.edu pull request #301
Opened 2024-08-21 18:15 UTC by SalazarJosh

<card> component now takes a heading level with default value of 3. The only page that passes a non-default value is the news landing page to ensure proper hierarchy. Also changed event card heading level from 2 to 3.

<details open>
<summary> :hand:&nbsp;&nbsp;<strong>Wait!</strong></summary>

Let's make sure your pull request is ready. Ask yourself...

:white_check_mark:&nbsp;&nbsp;"Did I do a good job testing my own code?"
:white_check_mark:&nbsp;&nbsp;"Is my code easy to read and understand?"
:white_check_mark:&nbsp;&nbsp;"Have I written unit tests? Do the unit tests fully cover my code?"
:white_check_mark:&nbsp;&nbsp;"Have I tested the repository's behavior to make sure my code didn't break anything?"
:negative_squared_cross_mark:&nbsp;&nbsp;"Did I include unrelated work that could be in its own pull request?"

Once you are ready, be sure to delete this `details` section before opening your pull request.
</details>

# Overview
Talk about the intent and scope of the original issue. Go over the general changes that have been made between this branch and the branch the pull request will merge into. Displaying screenshots can help!

Add links to any documentation or issues that can help give more background information. Is the pull request related to a GitHub or JIRA issue? Link to them while using [closing keywords](https://docs.github.com/articles/closing-issues-using-keywords), like so:

> This pull request resolves/closes/fixes [WEBSITE-1234](https://mlit.atlassian.net/browse/WEBSITE-1234).

## Anything else?
_Optional_. If appropriate, provide additional notes the reviewers should be made aware of. They can be about any "gotchas" or even changes that are expected to be made in the future, but are not applied to this pull request.

## Testing
List instructions on how to test the pull request. Some examples:

- Make sure the PR is consistent in these browsers:
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [ ] Edge (the assignee was not able to test the pull request in this browser)
- Run accessibility tests:
  - [x] WAVE
  - [x] ARC Toolkit
  - [x] axe DevTools
- _How to use the feature_.

2024-08-27 13:29 UTC, erinesullivan requested changes
Do I see the changes being made? Yes. The only change I'm requesting is on [Cafés](https://deploy-preview-301--future-wwwlib-previews.netlify.app/visit-and-study/cafes-and-wellbeing/cafes/) because switching from the paragraph to a heading added extra spacing between the text and images.

2024-08-30 16:20 UTC, SalazarJosh reviewed
Extra padding on card panels removed. Thanks for pointing that out @erinesullivan!

2024-08-30 19:53 UTC, erinesullivan commented on src/reusable/card.js
> +        <Heading level={headingLevel} css={{ marginTop: '0 !important' }}>
I agree with you that `!important` is messy, but it gets the job done. Two other options are:
1. Replacing `css` with `style`. It's simpler, but then you have inline styling:
```
style={{ marginTop: '0' }}
```
2. Add a class to the parent `div` and then update the `css` for `Heading` to:
```
css={{ '[data-panel] .parent-class &': { marginTop: '0' }}}
```

It's up to you. I'm fine with the current option or the other two options.

2024-09-05 14:26 UTC, erinesullivan approved these changes
👍🏻 Looks good!

2024-09-05 14:46 UTC, merged